import { fastfetchModules, defaultModuleValues } from "./fastfetch-modules";
import type { Distro } from "./store";
import type { KittyTheme } from "./kitty-presets";

function getLogoKey(distro: Distro): string {
  const map: Record<string, string> = {
    Arch: "arch",
    Fedora: "fedora",
    Debian: "debian",
    Ubuntu: "ubuntu",
    NixOS: "nixos",
    Mint: "linuxmint",
    Gentoo: "gentoo",
  };
  return map[distro] || "arch";
}

export function generateFastfetchConfig(params: {
  enabledModules: Record<string, boolean>;
  selectedDistro: Distro;
  username: string;
  hostname: string;
}): string {
  const { enabledModules, selectedDistro, username, hostname } = params;
  const logoKey = getLogoKey(selectedDistro);

  const modules = fastfetchModules
    .filter((m) => enabledModules[m.id])
    .map((m) => {
      if (m.id === "os") {
        return `    {
      type: "title",
      color: { user: "magenta", at: "red", host: "magenta" }
    }`;
      }
      return `    {
      type: "${m.key.toLowerCase()}"
    }`;
    });

  return `{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
    "type": "auto",
    "source": "${logoKey}",
    "width": 28,
    "height": 14,
    "padding": {
      "top": 2,
      "right": 4,
      "bottom": 2,
      "left": 2
    }
  },
  "display": {
    "separator": " ➜  ",
    "color": {
      "keys": "magenta"
    }
  },
  "modules": [
${modules.join(",\n")},
    {
      type: "colors",
      "symbol": "circle"
    }
  ]
}`;
}

export function generateKittyConfig(theme: KittyTheme, hasWallpaper = false): string {
  const lines = [
    `# Kitty Terminal Configuration`,
    `# Generated by Terminal Rice Studio`,
    ``,
    `# Font`,
    `font_family      JetBrains Mono`,
    `bold_font        auto`,
    `italic_font      auto`,
    `bold_italic_font auto`,
    `font_size        12.0`,
    ``,
    `# Cursor`,
    `cursor_shape     block`,
    `cursor_blink_interval 0.5`,
    `cursor_stop_blink_after 15.0`,
    ``,
    `# Scrollback`,
    `scrollback_lines 10000`,
    `scrollback_pager less -R`,
    ``,
    `# Mouse`,
    `mouse_hide_wait 3.0`,
    `url_style curly`,
    `open_url_with default`,
    ``,
    `# Window`,
    `window_padding_width 8`,
    `window_margin_width 0`,
    `hide_window_decorations titlebar-only`,
    `background_opacity 0.95`,
    ``,
    `# Performance`,
    `repaint_delay 10`,
    `input_delay 3`,
    `sync_to_monitor yes`,
    ``,
    `# Advanced`,
    `allow_remote_control yes`,
    `listen_on unix:/tmp/kitty`,
    ``,
    `# ─── Colors ───`,
    `foreground              ${theme.foreground}`,
    `background              ${theme.background}`,
    `selection_foreground    ${theme.background}`,
    `selection_background    ${theme.foreground}`,
    `cursor                  ${theme.cursor}`,
    `cursor_text_color       ${theme.background}`,
    ``,
    `# Black`,
    `color0                  ${theme.color0}`,
    `color8                  ${theme.color8}`,
    `# Red`,
    `color1                  ${theme.color1}`,
    `color9                  ${theme.color9}`,
    `# Green`,
    `color2                  ${theme.color2}`,
    `color10                 ${theme.color10}`,
    `# Yellow`,
    `color3                  ${theme.color3}`,
    `color11                 ${theme.color11}`,
    `# Blue`,
    `color4                  ${theme.color4}`,
    `color12                 ${theme.color12}`,
    `# Magenta`,
    `color5                  ${theme.color5}`,
    `color13                 ${theme.color13}`,
    `# Cyan`,
    `color6                  ${theme.color6}`,
    `color14                 ${theme.color14}`,
    `# White`,
    `color7                  ${theme.color7}`,
    `color15                 ${theme.color15}`,
  ];

  if (hasWallpaper) {
    lines.push(
      ``,
      `# ─── Wallpaper ───`,
      `# Coloque sua imagem em ~/.config/kitty/wallpaper.png`,
      `# Ou mude o caminho abaixo para onde quiser`,
      `background_image         wallpaper.png`,
      `background_image_layout scaled`,
      `background_opacity      0.85`,
    );
  }

  return lines.join("\n");
}
